export interface Country {
  code: string
  flag: string
  dial: string
  name: { hu: string; en: string }
}

export const COUNTRIES: Country[] = [
  { code: 'HU', flag: '🇭🇺', dial: '+36',   name: { hu: 'Magyarország',                     en: 'Hungary' } },
  { code: 'AF', flag: '🇦🇫', dial: '+93',   name: { hu: 'Afganisztán',                      en: 'Afghanistan' } },
  { code: 'AL', flag: '🇦🇱', dial: '+355',  name: { hu: 'Albánia',                          en: 'Albania' } },
  { code: 'DZ', flag: '🇩🇿', dial: '+213',  name: { hu: 'Algéria',                          en: 'Algeria' } },
  { code: 'AD', flag: '🇦🇩', dial: '+376',  name: { hu: 'Andorra',                          en: 'Andorra' } },
  { code: 'AO', flag: '🇦🇴', dial: '+244',  name: { hu: 'Angola',                           en: 'Angola' } },
  { code: 'AR', flag: '🇦🇷', dial: '+54',   name: { hu: 'Argentína',                        en: 'Argentina' } },
  { code: 'AM', flag: '🇦🇲', dial: '+374',  name: { hu: 'Örményország',                     en: 'Armenia' } },
  { code: 'AU', flag: '🇦🇺', dial: '+61',   name: { hu: 'Ausztrália',                       en: 'Australia' } },
  { code: 'AT', flag: '🇦🇹', dial: '+43',   name: { hu: 'Ausztria',                         en: 'Austria' } },
  { code: 'AZ', flag: '🇦🇿', dial: '+994',  name: { hu: 'Azerbajdzsán',                     en: 'Azerbaijan' } },
  { code: 'BH', flag: '🇧🇭', dial: '+973',  name: { hu: 'Bahrein',                          en: 'Bahrain' } },
  { code: 'BD', flag: '🇧🇩', dial: '+880',  name: { hu: 'Banglades',                        en: 'Bangladesh' } },
  { code: 'BY', flag: '🇧🇾', dial: '+375',  name: { hu: 'Fehéroroszország',                 en: 'Belarus' } },
  { code: 'BE', flag: '🇧🇪', dial: '+32',   name: { hu: 'Belgium',                          en: 'Belgium' } },
  { code: 'BZ', flag: '🇧🇿', dial: '+501',  name: { hu: 'Belize',                           en: 'Belize' } },
  { code: 'BJ', flag: '🇧🇯', dial: '+229',  name: { hu: 'Benin',                            en: 'Benin' } },
  { code: 'BT', flag: '🇧🇹', dial: '+975',  name: { hu: 'Bhután',                           en: 'Bhutan' } },
  { code: 'BO', flag: '🇧🇴', dial: '+591',  name: { hu: 'Bolívia',                          en: 'Bolivia' } },
  { code: 'BA', flag: '🇧🇦', dial: '+387',  name: { hu: 'Bosznia-Hercegovina',              en: 'Bosnia and Herzegovina' } },
  { code: 'BW', flag: '🇧🇼', dial: '+267',  name: { hu: 'Botswana',                         en: 'Botswana' } },
  { code: 'BR', flag: '🇧🇷', dial: '+55',   name: { hu: 'Brazília',                         en: 'Brazil' } },
  { code: 'BN', flag: '🇧🇳', dial: '+673',  name: { hu: 'Brunei',                           en: 'Brunei' } },
  { code: 'BG', flag: '🇧🇬', dial: '+359',  name: { hu: 'Bulgária',                         en: 'Bulgaria' } },
  { code: 'BF', flag: '🇧🇫', dial: '+226',  name: { hu: 'Burkina Faso',                     en: 'Burkina Faso' } },
  { code: 'BI', flag: '🇧🇮', dial: '+257',  name: { hu: 'Burundi',                          en: 'Burundi' } },
  { code: 'KH', flag: '🇰🇭', dial: '+855',  name: { hu: 'Kambodzsa',                        en: 'Cambodia' } },
  { code: 'CM', flag: '🇨🇲', dial: '+237',  name: { hu: 'Kamerun',                          en: 'Cameroon' } },
  { code: 'CA', flag: '🇨🇦', dial: '+1',    name: { hu: 'Kanada',                           en: 'Canada' } },
  { code: 'CV', flag: '🇨🇻', dial: '+238',  name: { hu: 'Zöld-foki Köztársaság',            en: 'Cape Verde' } },
  { code: 'CF', flag: '🇨🇫', dial: '+236',  name: { hu: 'Közép-afrikai Köztársaság',        en: 'Central African Republic' } },
  { code: 'TD', flag: '🇹🇩', dial: '+235',  name: { hu: 'Csád',                             en: 'Chad' } },
  { code: 'CL', flag: '🇨🇱', dial: '+56',   name: { hu: 'Chile',                            en: 'Chile' } },
  { code: 'CN', flag: '🇨🇳', dial: '+86',   name: { hu: 'Kína',                             en: 'China' } },
  { code: 'CO', flag: '🇨🇴', dial: '+57',   name: { hu: 'Kolumbia',                         en: 'Colombia' } },
  { code: 'KM', flag: '🇰🇲', dial: '+269',  name: { hu: 'Comore-szigetek',                  en: 'Comoros' } },
  { code: 'CG', flag: '🇨🇬', dial: '+242',  name: { hu: 'Kongói Köztársaság',               en: 'Congo' } },
  { code: 'CD', flag: '🇨🇩', dial: '+243',  name: { hu: 'Kongói Demokratikus Köztársaság',  en: 'Congo (DRC)' } },
  { code: 'CR', flag: '🇨🇷', dial: '+506',  name: { hu: 'Costa Rica',                       en: 'Costa Rica' } },
  { code: 'CI', flag: '🇨🇮', dial: '+225',  name: { hu: 'Elefántcsontpart',                 en: "Côte d'Ivoire" } },
  { code: 'HR', flag: '🇭🇷', dial: '+385',  name: { hu: 'Horvátország',                     en: 'Croatia' } },
  { code: 'CU', flag: '🇨🇺', dial: '+53',   name: { hu: 'Kuba',                             en: 'Cuba' } },
  { code: 'CY', flag: '🇨🇾', dial: '+357',  name: { hu: 'Ciprus',                           en: 'Cyprus' } },
  { code: 'CZ', flag: '🇨🇿', dial: '+420',  name: { hu: 'Csehország',                       en: 'Czechia' } },
  { code: 'DK', flag: '🇩🇰', dial: '+45',   name: { hu: 'Dánia',                            en: 'Denmark' } },
  { code: 'DJ', flag: '🇩🇯', dial: '+253',  name: { hu: 'Dzsibuti',                         en: 'Djibouti' } },
  { code: 'DO', flag: '🇩🇴', dial: '+1',    name: { hu: 'Dominikai Köztársaság',            en: 'Dominican Republic' } },
  { code: 'EC', flag: '🇪🇨', dial: '+593',  name: { hu: 'Ecuador',                          en: 'Ecuador' } },
  { code: 'EG', flag: '🇪🇬', dial: '+20',   name: { hu: 'Egyiptom',                         en: 'Egypt' } },
  { code: 'SV', flag: '🇸🇻', dial: '+503',  name: { hu: 'Salvador',                         en: 'El Salvador' } },
  { code: 'GQ', flag: '🇬🇶', dial: '+240',  name: { hu: 'Egyenlítői-Guinea',                en: 'Equatorial Guinea' } },
  { code: 'ER', flag: '🇪🇷', dial: '+291',  name: { hu: 'Eritrea',                          en: 'Eritrea' } },
  { code: 'EE', flag: '🇪🇪', dial: '+372',  name: { hu: 'Észtország',                       en: 'Estonia' } },
  { code: 'SZ', flag: '🇸🇿', dial: '+268',  name: { hu: 'Eswatini',                         en: 'Eswatini' } },
  { code: 'ET', flag: '🇪🇹', dial: '+251',  name: { hu: 'Etiópia',                          en: 'Ethiopia' } },
  { code: 'FJ', flag: '🇫🇯', dial: '+679',  name: { hu: 'Fidzsi-szigetek',                  en: 'Fiji' } },
  { code: 'FI', flag: '🇫🇮', dial: '+358',  name: { hu: 'Finnország',                       en: 'Finland' } },
  { code: 'FR', flag: '🇫🇷', dial: '+33',   name: { hu: 'Franciaország',                    en: 'France' } },
  { code: 'GA', flag: '🇬🇦', dial: '+241',  name: { hu: 'Gabon',                            en: 'Gabon' } },
  { code: 'GM', flag: '🇬🇲', dial: '+220',  name: { hu: 'Gambia',                           en: 'Gambia' } },
  { code: 'GE', flag: '🇬🇪', dial: '+995',  name: { hu: 'Grúzia',                           en: 'Georgia' } },
  { code: 'DE', flag: '🇩🇪', dial: '+49',   name: { hu: 'Németország',                      en: 'Germany' } },
  { code: 'GH', flag: '🇬🇭', dial: '+233',  name: { hu: 'Ghána',                            en: 'Ghana' } },
  { code: 'GR', flag: '🇬🇷', dial: '+30',   name: { hu: 'Görögország',                      en: 'Greece' } },
  { code: 'GT', flag: '🇬🇹', dial: '+502',  name: { hu: 'Guatemala',                        en: 'Guatemala' } },
  { code: 'GN', flag: '🇬🇳', dial: '+224',  name: { hu: 'Guinea',                           en: 'Guinea' } },
  { code: 'GW', flag: '🇬🇼', dial: '+245',  name: { hu: 'Bissau-Guinea',                    en: 'Guinea-Bissau' } },
  { code: 'GY', flag: '🇬🇾', dial: '+592',  name: { hu: 'Guyana',                           en: 'Guyana' } },
  { code: 'HT', flag: '🇭🇹', dial: '+509',  name: { hu: 'Haiti',                            en: 'Haiti' } },
  { code: 'HN', flag: '🇭🇳', dial: '+504',  name: { hu: 'Honduras',                         en: 'Honduras' } },
  { code: 'HK', flag: '🇭🇰', dial: '+852',  name: { hu: 'Hongkong',                         en: 'Hong Kong' } },
  { code: 'IS', flag: '🇮🇸', dial: '+354',  name: { hu: 'Izland',                           en: 'Iceland' } },
  { code: 'IN', flag: '🇮🇳', dial: '+91',   name: { hu: 'India',                            en: 'India' } },
  { code: 'ID', flag: '🇮🇩', dial: '+62',   name: { hu: 'Indonézia',                        en: 'Indonesia' } },
  { code: 'IR', flag: '🇮🇷', dial: '+98',   name: { hu: 'Irán',                             en: 'Iran' } },
  { code: 'IQ', flag: '🇮🇶', dial: '+964',  name: { hu: 'Irak',                             en: 'Iraq' } },
  { code: 'IE', flag: '🇮🇪', dial: '+353',  name: { hu: 'Írország',                         en: 'Ireland' } },
  { code: 'IL', flag: '🇮🇱', dial: '+972',  name: { hu: 'Izrael',                           en: 'Israel' } },
  { code: 'IT', flag: '🇮🇹', dial: '+39',   name: { hu: 'Olaszország',                      en: 'Italy' } },
  { code: 'JM', flag: '🇯🇲', dial: '+1',    name: { hu: 'Jamaica',                          en: 'Jamaica' } },
  { code: 'JP', flag: '🇯🇵', dial: '+81',   name: { hu: 'Japán',                            en: 'Japan' } },
  { code: 'JO', flag: '🇯🇴', dial: '+962',  name: { hu: 'Jordánia',                         en: 'Jordan' } },
  { code: 'KZ', flag: '🇰🇿', dial: '+7',    name: { hu: 'Kazahsztán',                       en: 'Kazakhstan' } },
  { code: 'KE', flag: '🇰🇪', dial: '+254',  name: { hu: 'Kenya',                            en: 'Kenya' } },
  { code: 'KW', flag: '🇰🇼', dial: '+965',  name: { hu: 'Kuvait',                           en: 'Kuwait' } },
  { code: 'KG', flag: '🇰🇬', dial: '+996',  name: { hu: 'Kirgizisztán',                     en: 'Kyrgyzstan' } },
  { code: 'LA', flag: '🇱🇦', dial: '+856',  name: { hu: 'Laosz',                            en: 'Laos' } },
  { code: 'LV', flag: '🇱🇻', dial: '+371',  name: { hu: 'Lettország',                       en: 'Latvia' } },
  { code: 'LB', flag: '🇱🇧', dial: '+961',  name: { hu: 'Libanon',                          en: 'Lebanon' } },
  { code: 'LS', flag: '🇱🇸', dial: '+266',  name: { hu: 'Lesotho',                          en: 'Lesotho' } },
  { code: 'LR', flag: '🇱🇷', dial: '+231',  name: { hu: 'Libéria',                          en: 'Liberia' } },
  { code: 'LY', flag: '🇱🇾', dial: '+218',  name: { hu: 'Líbia',                            en: 'Libya' } },
  { code: 'LI', flag: '🇱🇮', dial: '+423',  name: { hu: 'Liechtenstein',                    en: 'Liechtenstein' } },
  { code: 'LT', flag: '🇱🇹', dial: '+370',  name: { hu: 'Litvánia',                         en: 'Lithuania' } },
  { code: 'LU', flag: '🇱🇺', dial: '+352',  name: { hu: 'Luxemburg',                        en: 'Luxembourg' } },
  { code: 'MO', flag: '🇲🇴', dial: '+853',  name: { hu: 'Makaó',                            en: 'Macao' } },
  { code: 'MG', flag: '🇲🇬', dial: '+261',  name: { hu: 'Madagaszkár',                      en: 'Madagascar' } },
  { code: 'MW', flag: '🇲🇼', dial: '+265',  name: { hu: 'Malawi',                           en: 'Malawi' } },
  { code: 'MY', flag: '🇲🇾', dial: '+60',   name: { hu: 'Malajzia',                         en: 'Malaysia' } },
  { code: 'MV', flag: '🇲🇻', dial: '+960',  name: { hu: 'Maldív-szigetek',                  en: 'Maldives' } },
  { code: 'ML', flag: '🇲🇱', dial: '+223',  name: { hu: 'Mali',                             en: 'Mali' } },
  { code: 'MT', flag: '🇲🇹', dial: '+356',  name: { hu: 'Málta',                            en: 'Malta' } },
  { code: 'MR', flag: '🇲🇷', dial: '+222',  name: { hu: 'Mauritánia',                       en: 'Mauritania' } },
  { code: 'MU', flag: '🇲🇺', dial: '+230',  name: { hu: 'Mauritius',                        en: 'Mauritius' } },
  { code: 'MX', flag: '🇲🇽', dial: '+52',   name: { hu: 'Mexikó',                           en: 'Mexico' } },
  { code: 'MD', flag: '🇲🇩', dial: '+373',  name: { hu: 'Moldova',                          en: 'Moldova' } },
  { code: 'MC', flag: '🇲🇨', dial: '+377',  name: { hu: 'Monaco',                           en: 'Monaco' } },
  { code: 'MN', flag: '🇲🇳', dial: '+976',  name: { hu: 'Mongólia',                         en: 'Mongolia' } },
  { code: 'ME', flag: '🇲🇪', dial: '+382',  name: { hu: 'Montenegró',                       en: 'Montenegro' } },
  { code: 'MA', flag: '🇲🇦', dial: '+212',  name: { hu: 'Marokkó',                          en: 'Morocco' } },
  { code: 'MZ', flag: '🇲🇿', dial: '+258',  name: { hu: 'Mozambik',                         en: 'Mozambique' } },
  { code: 'MM', flag: '🇲🇲', dial: '+95',   name: { hu: 'Mianmar',                          en: 'Myanmar' } },
  { code: 'NA', flag: '🇳🇦', dial: '+264',  name: { hu: 'Namíbia',                          en: 'Namibia' } },
  { code: 'NP', flag: '🇳🇵', dial: '+977',  name: { hu: 'Nepál',                            en: 'Nepal' } },
  { code: 'NL', flag: '🇳🇱', dial: '+31',   name: { hu: 'Hollandia',                        en: 'Netherlands' } },
  { code: 'NZ', flag: '🇳🇿', dial: '+64',   name: { hu: 'Új-Zéland',                        en: 'New Zealand' } },
  { code: 'NI', flag: '🇳🇮', dial: '+505',  name: { hu: 'Nicaragua',                        en: 'Nicaragua' } },
  { code: 'NE', flag: '🇳🇪', dial: '+227',  name: { hu: 'Niger',                            en: 'Niger' } },
  { code: 'NG', flag: '🇳🇬', dial: '+234',  name: { hu: 'Nigéria',                          en: 'Nigeria' } },
  { code: 'KP', flag: '🇰🇵', dial: '+850',  name: { hu: 'Észak-Korea',                      en: 'North Korea' } },
  { code: 'MK', flag: '🇲🇰', dial: '+389',  name: { hu: 'Észak-Macedónia',                  en: 'North Macedonia' } },
  { code: 'NO', flag: '🇳🇴', dial: '+47',   name: { hu: 'Norvégia',                         en: 'Norway' } },
  { code: 'OM', flag: '🇴🇲', dial: '+968',  name: { hu: 'Omán',                             en: 'Oman' } },
  { code: 'PK', flag: '🇵🇰', dial: '+92',   name: { hu: 'Pakisztán',                        en: 'Pakistan' } },
  { code: 'PS', flag: '🇵🇸', dial: '+970',  name: { hu: 'Palesztina',                       en: 'Palestine' } },
  { code: 'PA', flag: '🇵🇦', dial: '+507',  name: { hu: 'Panama',                           en: 'Panama' } },
  { code: 'PG', flag: '🇵🇬', dial: '+675',  name: { hu: 'Pápua Új-Guinea',                  en: 'Papua New Guinea' } },
  { code: 'PY', flag: '🇵🇾', dial: '+595',  name: { hu: 'Paraguay',                         en: 'Paraguay' } },
  { code: 'PE', flag: '🇵🇪', dial: '+51',   name: { hu: 'Peru',                             en: 'Peru' } },
  { code: 'PH', flag: '🇵🇭', dial: '+63',   name: { hu: 'Fülöp-szigetek',                   en: 'Philippines' } },
  { code: 'PL', flag: '🇵🇱', dial: '+48',   name: { hu: 'Lengyelország',                    en: 'Poland' } },
  { code: 'PT', flag: '🇵🇹', dial: '+351',  name: { hu: 'Portugália',                       en: 'Portugal' } },
  { code: 'PR', flag: '🇵🇷', dial: '+1',    name: { hu: 'Puerto Rico',                      en: 'Puerto Rico' } },
  { code: 'QA', flag: '🇶🇦', dial: '+974',  name: { hu: 'Katar',                            en: 'Qatar' } },
  { code: 'RO', flag: '🇷🇴', dial: '+40',   name: { hu: 'Románia',                          en: 'Romania' } },
  { code: 'RU', flag: '🇷🇺', dial: '+7',    name: { hu: 'Oroszország',                      en: 'Russia' } },
  { code: 'RW', flag: '🇷🇼', dial: '+250',  name: { hu: 'Ruanda',                           en: 'Rwanda' } },
  { code: 'SM', flag: '🇸🇲', dial: '+378',  name: { hu: 'San Marino',                       en: 'San Marino' } },
  { code: 'SA', flag: '🇸🇦', dial: '+966',  name: { hu: 'Szaúd-Arábia',                     en: 'Saudi Arabia' } },
  { code: 'SN', flag: '🇸🇳', dial: '+221',  name: { hu: 'Szenegál',                         en: 'Senegal' } },
  { code: 'RS', flag: '🇷🇸', dial: '+381',  name: { hu: 'Szerbia',                          en: 'Serbia' } },
  { code: 'SC', flag: '🇸🇨', dial: '+248',  name: { hu: 'Seychelle-szigetek',               en: 'Seychelles' } },
  { code: 'SL', flag: '🇸🇱', dial: '+232',  name: { hu: 'Sierra Leone',                     en: 'Sierra Leone' } },
  { code: 'SG', flag: '🇸🇬', dial: '+65',   name: { hu: 'Szingapúr',                        en: 'Singapore' } },
  { code: 'SK', flag: '🇸🇰', dial: '+421',  name: { hu: 'Szlovákia',                        en: 'Slovakia' } },
  { code: 'SI', flag: '🇸🇮', dial: '+386',  name: { hu: 'Szlovénia',                        en: 'Slovenia' } },
  { code: 'SO', flag: '🇸🇴', dial: '+252',  name: { hu: 'Szomália',                         en: 'Somalia' } },
  { code: 'ZA', flag: '🇿🇦', dial: '+27',   name: { hu: 'Dél-afrikai Köztársaság',          en: 'South Africa' } },
  { code: 'KR', flag: '🇰🇷', dial: '+82',   name: { hu: 'Dél-Korea',                        en: 'South Korea' } },
  { code: 'SS', flag: '🇸🇸', dial: '+211',  name: { hu: 'Dél-Szudán',                       en: 'South Sudan' } },
  { code: 'ES', flag: '🇪🇸', dial: '+34',   name: { hu: 'Spanyolország',                    en: 'Spain' } },
  { code: 'LK', flag: '🇱🇰', dial: '+94',   name: { hu: 'Srí Lanka',                        en: 'Sri Lanka' } },
  { code: 'SD', flag: '🇸🇩', dial: '+249',  name: { hu: 'Szudán',                           en: 'Sudan' } },
  { code: 'SR', flag: '🇸🇷', dial: '+597',  name: { hu: 'Suriname',                         en: 'Suriname' } },
  { code: 'SE', flag: '🇸🇪', dial: '+46',   name: { hu: 'Svédország',                       en: 'Sweden' } },
  { code: 'CH', flag: '🇨🇭', dial: '+41',   name: { hu: 'Svájc',                            en: 'Switzerland' } },
  { code: 'SY', flag: '🇸🇾', dial: '+963',  name: { hu: 'Szíria',                           en: 'Syria' } },
  { code: 'TW', flag: '🇹🇼', dial: '+886',  name: { hu: 'Tajvan',                           en: 'Taiwan' } },
  { code: 'TJ', flag: '🇹🇯', dial: '+992',  name: { hu: 'Tádzsikisztán',                    en: 'Tajikistan' } },
  { code: 'TZ', flag: '🇹🇿', dial: '+255',  name: { hu: 'Tanzánia',                         en: 'Tanzania' } },
  { code: 'TH', flag: '🇹🇭', dial: '+66',   name: { hu: 'Thaiföld',                         en: 'Thailand' } },
  { code: 'TL', flag: '🇹🇱', dial: '+670',  name: { hu: 'Kelet-Timor',                      en: 'Timor-Leste' } },
  { code: 'TG', flag: '🇹🇬', dial: '+228',  name: { hu: 'Togo',                             en: 'Togo' } },
  { code: 'TN', flag: '🇹🇳', dial: '+216',  name: { hu: 'Tunézia',                          en: 'Tunisia' } },
  { code: 'TR', flag: '🇹🇷', dial: '+90',   name: { hu: 'Törökország',                      en: 'Turkey' } },
  { code: 'TM', flag: '🇹🇲', dial: '+993',  name: { hu: 'Türkmenisztán',                    en: 'Turkmenistan' } },
  { code: 'UG', flag: '🇺🇬', dial: '+256',  name: { hu: 'Uganda',                           en: 'Uganda' } },
  { code: 'UA', flag: '🇺🇦', dial: '+380',  name: { hu: 'Ukrajna',                          en: 'Ukraine' } },
  { code: 'AE', flag: '🇦🇪', dial: '+971',  name: { hu: 'Egyesült Arab Emírségek',          en: 'United Arab Emirates' } },
  { code: 'GB', flag: '🇬🇧', dial: '+44',   name: { hu: 'Egyesült Királyság',               en: 'United Kingdom' } },
  { code: 'US', flag: '🇺🇸', dial: '+1',    name: { hu: 'Egyesült Államok',                 en: 'United States' } },
  { code: 'UY', flag: '🇺🇾', dial: '+598',  name: { hu: 'Uruguay',                          en: 'Uruguay' } },
  { code: 'UZ', flag: '🇺🇿', dial: '+998',  name: { hu: 'Üzbegisztán',                      en: 'Uzbekistan' } },
  { code: 'VE', flag: '🇻🇪', dial: '+58',   name: { hu: 'Venezuela',                        en: 'Venezuela' } },
  { code: 'VN', flag: '🇻🇳', dial: '+84',   name: { hu: 'Vietnám',                          en: 'Vietnam' } },
  { code: 'YE', flag: '🇾🇪', dial: '+967',  name: { hu: 'Jemen',                            en: 'Yemen' } },
  { code: 'ZM', flag: '🇿🇲', dial: '+260',  name: { hu: 'Zambia',                           en: 'Zambia' } },
  { code: 'ZW', flag: '🇿🇼', dial: '+263',  name: { hu: 'Zimbabwe',                         en: 'Zimbabwe' } },
]

export function findCountry(code: string): Country {
  return COUNTRIES.find(c => c.code === code) ?? COUNTRIES[0]
}
